apiVersion: v1
kind: Service
metadata:
  name: cap-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: cap-deployment
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
